{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "72c68378-cb4e-47d1-bf10-792280d60bde",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from reportlab.platypus import SimpleDocTemplate, Paragraph, Image, Spacer\n",
    "from reportlab.lib.styles import getSampleStyleSheet\n",
    "from reportlab.lib.pagesizes import A4\n",
    "from datetime import datetime\n",
    "\n",
    "# -----------------------------\n",
    "# PATH CONFIGURATION (RELATIVE)\n",
    "# -----------------------------\n",
    "DATA_PATH = os.path.join(\"data\", \"sales_data_q1_2025.csv\")\n",
    "VISUALS_DIR = \"visuals\"\n",
    "REPORTS_DIR = \"reports\"\n",
    "REPORT_PATH = os.path.join(\n",
    "    REPORTS_DIR,\n",
    "    \"Automated_Sales_Report_Q1_2025.pdf\"\n",
    ")\n",
    "\n",
    "# Create output directories if they don't exist\n",
    "os.makedirs(VISUALS_DIR, exist_ok=True)\n",
    "os.makedirs(REPORTS_DIR, exist_ok=True)\n",
    "\n",
    "# -----------------------------\n",
    "# STEP 1: LOAD & PREPARE DATA\n",
    "# -----------------------------\n",
    "df = pd.read_csv(DATA_PATH, parse_dates=[\"Date\"])\n",
    "df[\"Month\"] = df[\"Date\"].dt.to_period(\"M\").astype(str)\n",
    "\n",
    "# -----------------------------\n",
    "# STEP 2: KPI ANALYSIS\n",
    "# -----------------------------\n",
    "total_revenue = round(df[\"Revenue\"].sum(), 2)\n",
    "total_orders = df[\"Order_ID\"].nunique()\n",
    "avg_order_value = round(total_revenue / total_orders, 2)\n",
    "\n",
    "revenue_by_region = (\n",
    "    df.groupby(\"Region\")[\"Revenue\"]\n",
    "    .sum()\n",
    "    .sort_values(ascending=False)\n",
    ")\n",
    "\n",
    "monthly_revenue = (\n",
    "    df.groupby(\"Month\")[\"Revenue\"]\n",
    "    .sum()\n",
    ")\n",
    "\n",
    "top_products = (\n",
    "    df.groupby(\"Product\")[\"Revenue\"]\n",
    "    .sum()\n",
    "    .sort_values(ascending=False)\n",
    "    .head(5)\n",
    ")\n",
    "\n",
    "# -----------------------------\n",
    "# STEP 3: VISUALIZATIONS\n",
    "# -----------------------------\n",
    "\n",
    "# Monthly Revenue Trend\n",
    "plt.figure()\n",
    "monthly_revenue.plot()\n",
    "plt.title(\"Monthly Revenue Trend (Q1 2025)\")\n",
    "plt.xlabel(\"Month\")\n",
    "plt.ylabel(\"Revenue\")\n",
    "trend_path = os.path.join(VISUALS_DIR, \"monthly_revenue.png\")\n",
    "plt.savefig(trend_path)\n",
    "plt.close()\n",
    "\n",
    "# Revenue by Region\n",
    "plt.figure()\n",
    "revenue_by_region.plot(kind=\"bar\")\n",
    "plt.title(\"Revenue by Region\")\n",
    "plt.xlabel(\"Region\")\n",
    "plt.ylabel(\"Revenue\")\n",
    "region_path = os.path.join(VISUALS_DIR, \"revenue_by_region.png\")\n",
    "plt.savefig(region_path)\n",
    "plt.close()\n",
    "\n",
    "# Top Products by Revenue\n",
    "plt.figure()\n",
    "top_products.plot(kind=\"bar\")\n",
    "plt.title(\"Top 5 Products by Revenue\")\n",
    "plt.xlabel(\"Product\")\n",
    "plt.ylabel(\"Revenue\")\n",
    "product_path = os.path.join(VISUALS_DIR, \"top_products.png\")\n",
    "plt.savefig(product_path)\n",
    "plt.close()\n",
    "\n",
    "# -----------------------------\n",
    "# STEP 4: PDF REPORT GENERATION\n",
    "# -----------------------------\n",
    "styles = getSampleStyleSheet()\n",
    "report = SimpleDocTemplate(REPORT_PATH, pagesize=A4)\n",
    "elements = []\n",
    "\n",
    "# Report Title\n",
    "elements.append(\n",
    "    Paragraph(\n",
    "        \"Automated Sales Performance Report – Q1 2025\",\n",
    "        styles[\"Title\"]\n",
    "    )\n",
    ")\n",
    "elements.append(Spacer(1, 12))\n",
    "\n",
    "# Executive Summary\n",
    "summary = f\"\"\"\n",
    "<b>Report Generated:</b> {datetime.today().strftime('%Y-%m-%d')}<br/>\n",
    "<b>Total Revenue:</b> ${total_revenue}<br/>\n",
    "<b>Total Orders:</b> {total_orders}<br/>\n",
    "<b>Average Order Value:</b> ${avg_order_value}\n",
    "\"\"\"\n",
    "elements.append(Paragraph(summary, styles[\"Normal\"]))\n",
    "elements.append(Spacer(1, 16))\n",
    "\n",
    "# Charts Section\n",
    "elements.append(Paragraph(\"Monthly Revenue Trend\", styles[\"Heading2\"]))\n",
    "elements.append(Image(trend_path, width=400, height=250))\n",
    "elements.append(Spacer(1, 14))\n",
    "\n",
    "elements.append(Paragraph(\"Revenue by Region\", styles[\"Heading2\"]))\n",
    "elements.append(Image(region_path, width=400, height=250))\n",
    "elements.append(Spacer(1, 14))\n",
    "\n",
    "elements.append(Paragraph(\"Top Products by Revenue\", styles[\"Heading2\"]))\n",
    "elements.append(Image(product_path, width=400, height=250))\n",
    "\n",
    "# Build PDF\n",
    "report.build(elements)\n",
    "\n",
    "print(\"✅ Automated report generated successfully.\")\n",
    "print(f\"📄 Output file: {REPORT_PATH}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
